name: Publish npm

# ──────────────────────────────────────────────────────────────
# Trigger:
#   • Any push to main that touches package.json or src/**
#   • Manual run (workflow_dispatch) with release-type input
# ──────────────────────────────────────────────────────────────
on:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'src/**'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Version bump (patch / minor / major)'
        required: false
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # allow the action to commit & push
      packages: write # allow npm publish

    steps:
      # ───────────── Git checkout ─────────────
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # tags are needed for version bump

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # ───────────── Auto-increment version ──
      - name: Bump package version & push tag
        id: bump
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          default: ${{ github.event.inputs.release_type || 'patch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm validate

      # ───────────── Publish to npmjs ────────
      - name: Publish package
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
